version: '1'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - '3001:80'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:80'
